events {}

http {
    server {
        listen 80;

        # Route API calls (REST, GraphQL) to the backend
        location /api/ {
            proxy_pass http://url-service:3001/; # 'url-service' is our docker service name
        }
        
        location /graphql {
            proxy_pass http://url-service:3001/graphql;
        }

        # Route WebSocket connections to the backend
        location /socket.io/ {
            proxy_pass http://url-service:3001/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

        # Route all other traffic to the frontend
        location / {
            proxy_pass http://frontend:3000; # 'frontend' is our docker service name
        }
    }
}

